[boxoffice_weekly]
title = "다음 영화 ─ 박스오피스 ─ 주간"
url = "https://movie.daum.net/ranking/boxoffice/weekly"
entrySelector = "ol.list_movieranking li"
titleSelector = "strong.tit_item a.link_txt"
linkSelector = "a.link_txt"
contentSelector = "span.info_txt:nth-child(2)"
imageSelector = "div.poster_movie img.img_thumb"
waitUntil = "networkidle"

[boxoffice_monthly]
title = "다음 영화 ─ 박스오피스 ─ 월간"
url = "https://movie.daum.net/ranking/boxoffice/monthly"
entrySelector = "ol.list_movieranking li"
titleSelector = "strong.tit_item a.link_txt"
linkSelector = "a.link_txt"
contentSelector = "span.info_txt:nth-child(2)"
imageSelector = "div.poster_movie img.img_thumb"
waitUntil = "networkidle"

[boxoffice_yearly]
title = "다음 영화 ─ 박스오피스 ─ 연간"
url = "https://movie.daum.net/ranking/boxoffice/yearly"
entrySelector = "ol.list_movieranking li"
titleSelector = "strong.tit_item a.link_txt"
linkSelector = "a.link_txt"
contentSelector = "span.info_txt:nth-child(2)"
imageSelector = "div.poster_movie img.img_thumb"
waitUntil = "networkidle"

[premovie_theater_y]
title = "다음영화 영화관 ─ 현재상영"
url = "https://movie.daum.net/premovie/theater?flag=Y"
entrySelector = "div.box_movie ol li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[premovie_theater_c]
title = "다음영화 영화관 ─ 개봉예정"
url = "https://movie.daum.net/premovie/theater?flag=C"
entrySelector = "div.box_movie ol li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[premovie_netflix_c]
title = "[다음영화] 넷플릭스 ─ 종료예정"
url = "https://movie.daum.net/premovie/netflix?flag=C"
entrySelector = "ul.list_movieranking.aniposter_ott li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[premovie_netflix_y]
title = "[다음영화] 넷플릭스 ─ 공개예정"
url = "https://movie.daum.net/premovie/netflix?flag=Y"
entrySelector = "ul.list_movieranking.aniposter_ott li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[premovie_watcha_c]
title = "[다음영화] 왓챠 ─ 종료예정"
url = "https://movie.daum.net/premovie/watcha?flag=C"
entrySelector = "ul.list_movieranking.aniposter_ott li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[premovie_watcha_y]
title = "[다음영화] 왓챠 ─ 공개예정"
url = "https://movie.daum.net/premovie/watcha?flag=Y"
entrySelector = "ul.list_movieranking.aniposter_ott li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[premovie_kakaopage_c]
title = "[다음영화] 카카오페이지 ─ 종료예정"
url = "https://movie.daum.net/premovie/kakaopage?flag=C"
entrySelector = "ul.list_movieranking.aniposter_ott li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[premovie_kakaopage_y]
title = "[다음영화] 카카오페이지 ─ 공개예정"
url = "https://movie.daum.net/premovie/kakaopage?flag=Y"
entrySelector = "ul.list_movieranking.aniposter_ott li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[news_recent]
title = "다음영화 뉴스 ─ 최신"
url = "https://movie.daum.net/contents/news?type=recent"
entrySelector = "div.box_movienews ul li"
titleSelector = "strong a[class='link_txt']"
linkSelector = "strong a[class='link_txt']"
imageSelector = "span[class='bg_img']"
contentSelector = "p[class='desc_thumb'] a"
dateSelector = "div.info_thumb span.txt_info:nth-child(1)"
dateFormat = "yyyy.MM.dd"
waitForSelector = "ul.list_movienews"
onFail = "stale"

[news_popular]
title = "다음영화 뉴스 ─ 인기"
url = "https://movie.daum.net/contents/news?type=popular"
entrySelector = "div.box_movienews > ol > li"
titleSelector = "strong a[class='link_txt']"
linkSelector = "strong a[class='link_txt']"
imageSelector = "span[class='bg_img']"
contentSelector = "p[class='desc_thumb'] a"
dateSelector = "div.info_thumb span.txt_info:nth-child(1)"
dateFormat = "yyyy.MM.dd"
waitForSelector = "ol.list_movienews"
onFail = "stale"

[magazine]
title = "다음 영화 ─ 매거진"
url = "https://movie.daum.net/contents/1boon"
entrySelector = "ul.list_contents li"
titleSelector = "strong a.link_txt"
linkSelector = "a.link_txt"
contentSelector = "span.txt_info"
imageSelector = "span.bg_img"
waitUntil = "networkidle"
onFail = "stale"

[brunch]
title = "다음 영화 ─ 브런치"
url = "https://movie.daum.net/contents/brunch"
entrySelector = "ul.list_contents li"
titleSelector = "strong a.link_txt"
linkSelector = "a.link_txt"
contentSelector = "span.txt_info"
imageSelector = "span.bg_img"
waitUntil = "networkidle"
onFail = "stale"
