[news_recent]
title = "다음영화 뉴스 ─ 최신"
url = "https://movie.daum.net/contents/news?type=recent"
entrySelector = "div.box_movienews ul li"
titleSelector = "strong a[class='link_txt']"
linkSelector = "strong a[class='link_txt']"
imageSelector = "span[class='bg_img']"
contentSelector = "p[class='desc_thumb'] a"
dateSelector = "div.info_thumb span.txt_info:nth-child(1)"
dateFormat = "yyyy.MM.dd"
waitForSelector = "ul.list_movienews"
onFail = "stale"

[news_popular]
title = "다음영화 뉴스 ─ 인기"
url = "https://movie.daum.net/contents/news?type=popular"
entrySelector = "div.box_movienews > ol > li"
titleSelector = "strong a[class='link_txt']"
linkSelector = "strong a[class='link_txt']"
imageSelector = "span[class='bg_img']"
contentSelector = "p[class='desc_thumb'] a"
dateSelector = "div.info_thumb span.txt_info:nth-child(1)"
dateFormat = "yyyy.MM.dd"
waitForSelector = "ol.list_movienews"
onFail = "stale"

[magazine]
title = "다음 영화 ─ 매거진"
url = "https://movie.daum.net/contents/1boon"
entrySelector = "ul.list_contents li"
titleSelector = "strong a.link_txt"
linkSelector = "a.link_txt"
contentSelector = "span.txt_info"
imageSelector = "span.bg_img"
waitUntil = "networkidle"
onFail = "stale"

[brunch]
title = "다음 영화 ─ 브런치"
url = "https://movie.daum.net/contents/brunch"
entrySelector = "ul.list_contents li"
titleSelector = "strong a.link_txt"
linkSelector = "a.link_txt"
contentSelector = "span.txt_info"
imageSelector = "span.bg_img"
waitUntil = "networkidle"
onFail = "stale"
